### ISSUE TITLE
same parameter but not work for schnell

### ISSUE THREAD

**Issue by xueqing0622** [TheMistoAI/MistoControlNet-Flux-dev#10]
same parameter but not work for schnell
still show:
!!! Exception during processing !!! The size of tensor a (3072) must match the size of tensor b (256) at non-singleton dimension 1
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\MistoControlNet-Flux-dev\nodes.py", line 209, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\MistoControlNet-Flux-dev\modules\utils.py", line 429, in denoise_controlnet
    pred = forward_mistoCN(
           ^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\MistoControlNet-Flux-dev\modules\utils.py", line 358, in forward_mistoCN
    vec = vec + model.guidance_in(timestep_embedding(guidance, 256))
          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (3072) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by baizh0u** [comment]
This cn is not for Flux.schnell model, only for Flux.dev
