### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x3072)

### ISSUE THREAD

**Issue by dave-ct** [TheMistoAI/MistoControlNet-Flux-dev#19]
Hi

I get the below error

I have tried to updated comfyui and update all the installed custom nodes but I get the below error with the KsamplerTheMisto

Any suggestions?

# ComfyUI Error Report
## Error Details
- **Node Type:** KSamplerTheMisto
- **Exception Type:** RuntimeError
- **Exception Message:** mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x3072)
## Stack Trace
```
  File "/home/pi/codes/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/pi/codes/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/pi/codes/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/pi/codes/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/nodes.py", line 209, in sampling
    x = denoise_controlnet(

  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/utils.py", line 419, in denoise_controlnet
    block_res_samples, single_block_res_samples = controlnet(

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/misto_controlnet.py", line 218, in forward
    vec = vec + self.vector_in(y)

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/utils.py", line 87, in forward
    return self.out_layer(self.silu(self.in_layer(x)))

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)

```
## System Information
- **ComfyUI Version:** v0.2.0-2-g00a5d08
- **Arguments:** main.py --listen
- **OS:** posix
- **Python Version:** 3.10.14 (main, Apr 27 2024, 21:17:55) [GCC 13.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25390678016
  - **VRAM Free:** 6958485720
  - **Torch VRAM Total:** 16374562816
  - **Torch VRAM Free:** 12652760

## Logs
```
2024-09-03 17:46:53,616 - root - INFO - Total VRAM 24214 MB, total RAM 128617 MB
2024-09-03 17:46:53,616 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-03 17:46:53,617 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-03 17:46:53,617 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-09-03 17:46:53,947 - root - INFO - Using pytorch cross attention
2024-09-03 17:46:54,189 - root - INFO - [Prompt Server] web root: /home/pi/codes/ComfyUI/web
2024-09-03 17:46:54,543 - root - INFO - Total VRAM 24214 MB, total RAM 128617 MB
2024-09-03 17:46:54,543 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-03 17:46:54,543 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-03 17:46:54,543 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-09-03 17:46:54,677 - root - WARNING - Traceback (most recent call last):
  File "/home/pi/codes/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pi/codes/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/pi/codes/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

2024-09-03 17:46:54,678 - root - WARNING - Cannot import /home/pi/codes/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'insightface'
2024-09-03 17:46:54,908 - root - INFO - 
Import times for custom nodes:
2024-09-03 17:46:54,908 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-03 17:46:54,908 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/cg-use-everywhere
2024-09-03 17:46:54,908 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/comfy-image-saver
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/rgthree-comfy
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/x-flux-comfyui
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI_essentials
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
2024-09-03 17:46:54,909 - root - INFO -    0.0 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-SAM2
2024-09-03 17:46:54,909 - root - INFO -    0.1 seconds: /home/pi/codes/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-09-03 17:46:54,909 - root - INFO -    0.1 seconds: /home/pi/codes/ComfyUI/custom_nodes/comfyui_segment_anything
2024-09-03 17:46:54,909 - root - INFO -    0.1 seconds: /home/pi/codes/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-09-03 17:46:54,909 - root - INFO -    0.1 seconds (IMPORT FAILED): /home/pi/codes/ComfyUI/custom_nodes/comfyui-reactor-node
2024-09-03 17:46:54,909 - root - INFO - 
2024-09-03 17:46:54,914 - root - INFO - Starting server

2024-09-03 17:46:54,914 - root - INFO - To see the GUI go to: http://0.0.0.0:8188
2024-09-03 17:47:37,203 - root - INFO - got prompt
2024-09-03 17:47:37,480 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-09-03 17:47:37,480 - root - INFO - model_type FLUX
2024-09-03 17:47:38,560 - root - INFO - Using pytorch attention in VAE
2024-09-03 17:47:38,560 - root - INFO - Using pytorch attention in VAE
2024-09-03 17:47:38,682 - root - WARNING - clip missing: ['text_projection.weight']
2024-09-03 17:47:38,682 - root - WARNING - clip missing: ['text_model.embeddings.token_embedding.weight', 'text_model.embeddings.position_embedding.weight', 'text_model.encoder.layers.0.layer_norm1.weight', 'text_model.encoder.layers.0.layer_norm1.bias', 'text_model.encoder.layers.0.self_attn.q_proj.weight', 'text_model.encoder.layers.0.self_attn.q_proj.bias', 'text_model.encoder.layers.0.self_attn.k_proj.weight', 'text_model.encoder.layers.0.self_attn.k_proj.bias', 'text_model.encoder.layers.0.self_attn.v_proj.weight', 'text_model.encoder.layers.0.self_attn.v_proj.bias', 'text_model.encoder.layers.0.self_attn.out_proj.weight', 'text_model.encoder.layers.0.self_attn.out_proj.bias', 'text_model.encoder.layers.0.layer_norm2.weight', 'text_model.encoder.layers.0.layer_norm2.bias', 'text_model.encoder.layers.0.mlp.fc1.weight', 'text_model.encoder.layers.0.mlp.fc1.bias', 'text_model.encoder.layers.0.mlp.fc2.weight', 'text_model.encoder.layers.0.mlp.fc2.bias', 'text_model.encoder.layers.1.layer_norm1.weight', 'text_model.encoder.layers.1.layer_norm1.bias', 'text_model.encoder.layers.1.self_attn.q_proj.weight', 'text_model.encoder.layers.1.self_attn.q_proj.bias', 'text_model.encoder.layers.1.self_attn.k_proj.weight', 'text_model.encoder.layers.1.self_attn.k_proj.bias', 'text_model.encoder.layers.1.self_attn.v_proj.weight', 'text_model.encoder.layers.1.self_attn.v_proj.bias', 'text_model.encoder.layers.1.self_attn.out_proj.weight', 'text_model.encoder.layers.1.self_attn.out_proj.bias', 'text_model.encoder.layers.1.layer_norm2.weight', 'text_model.encoder.layers.1.layer_norm2.bias', 'text_model.encoder.layers.1.mlp.fc1.weight', 'text_model.encoder.layers.1.mlp.fc1.bias', 'text_model.encoder.layers.1.mlp.fc2.weight', 'text_model.encoder.layers.1.mlp.fc2.bias', 'text_model.encoder.layers.2.layer_norm1.weight', 'text_model.encoder.layers.2.layer_norm1.bias', 'text_model.encoder.layers.2.self_attn.q_proj.weight', 'text_model.encoder.layers.2.self_attn.q_proj.bias', 'text_model.encoder.layers.2.self_attn.k_proj.weight', 'text_model.encoder.layers.2.self_attn.k_proj.bias', 'text_model.encoder.layers.2.self_attn.v_proj.weight', 'text_model.encoder.layers.2.self_attn.v_proj.bias', 'text_model.encoder.layers.2.self_attn.out_proj.weight', 'text_model.encoder.layers.2.self_attn.out_proj.bias', 'text_model.encoder.layers.2.layer_norm2.weight', 'text_model.encoder.layers.2.layer_norm2.bias', 'text_model.encoder.layers.2.mlp.fc1.weight', 'text_model.encoder.layers.2.mlp.fc1.bias', 'text_model.encoder.layers.2.mlp.fc2.weight', 'text_model.encoder.layers.2.mlp.fc2.bias', 'text_model.encoder.layers.3.layer_norm1.weight', 'text_model.encoder.layers.3.layer_norm1.bias', 'text_model.encoder.layers.3.self_attn.q_proj.weight', 'text_model.encoder.layers.3.self_attn.q_proj.bias', 'text_model.encoder.layers.3.self_attn.k_proj.weight', 'text_model.encoder.layers.3.self_attn.k_proj.bias', 'text_model.encoder.layers.3.self_attn.v_proj.weight', 'text_model.encoder.layers.3.self_attn.v_proj.bias', 'text_model.encoder.layers.3.self_attn.out_proj.weight', 'text_model.encoder.layers.3.self_attn.out_proj.bias', 'text_model.encoder.layers.3.layer_norm2.weight', 'text_model.encoder.layers.3.layer_norm2.bias', 'text_model.encoder.layers.3.mlp.fc1.weight', 'text_model.encoder.layers.3.mlp.fc1.bias', 'text_model.encoder.layers.3.mlp.fc2.weight', 'text_model.encoder.layers.3.mlp.fc2.bias', 'text_model.encoder.layers.4.layer_norm1.weight', 'text_model.encoder.layers.4.layer_norm1.bias', 'text_model.encoder.layers.4.self_attn.q_proj.weight', 'text_model.encoder.layers.4.self_attn.q_proj.bias', 'text_model.encoder.layers.4.self_attn.k_proj.weight', 'text_model.encoder.layers.4.self_attn.k_proj.bias', 'text_model.encoder.layers.4.self_attn.v_proj.weight', 'text_model.encoder.layers.4.self_attn.v_proj.bias', 'text_model.encoder.layers.4.self_attn.out_proj.weight', 'text_model.encoder.layers.4.self_attn.out_proj.bias', 'text_model.encoder.layers.4.layer_norm2.weight', 'text_model.encoder.layers.4.layer_norm2.bias', 'text_model.encoder.layers.4.mlp.fc1.weight', 'text_model.encoder.layers.4.mlp.fc1.bias', 'text_model.encoder.layers.4.mlp.fc2.weight', 'text_model.encoder.layers.4.mlp.fc2.bias', 'text_model.encoder.layers.5.layer_norm1.weight', 'text_model.encoder.layers.5.layer_norm1.bias', 'text_model.encoder.layers.5.self_attn.q_proj.weight', 'text_model.encoder.layers.5.self_attn.q_proj.bias', 'text_model.encoder.layers.5.self_attn.k_proj.weight', 'text_model.encoder.layers.5.self_attn.k_proj.bias', 'text_model.encoder.layers.5.self_attn.v_proj.weight', 'text_model.encoder.layers.5.self_attn.v_proj.bias', 'text_model.encoder.layers.5.self_attn.out_proj.weight', 'text_model.encoder.layers.5.self_attn.out_proj.bias', 'text_model.encoder.layers.5.layer_norm2.weight', 'text_model.encoder.layers.5.layer_norm2.bias', 'text_model.encoder.layers.5.mlp.fc1.weight', 'text_model.encoder.layers.5.mlp.fc1.bias', 'text_model.encoder.layers.5.mlp.fc2.weight', 'text_model.encoder.layers.5.mlp.fc2.bias', 'text_model.encoder.layers.6.layer_norm1.weight', 'text_model.encoder.layers.6.layer_norm1.bias', 'text_model.encoder.layers.6.self_attn.q_proj.weight', 'text_model.encoder.layers.6.self_attn.q_proj.bias', 'text_model.encoder.layers.6.self_attn.k_proj.weight', 'text_model.encoder.layers.6.self_attn.k_proj.bias', 'text_model.encoder.layers.6.self_attn.v_proj.weight', 'text_model.encoder.layers.6.self_attn.v_proj.bias', 'text_model.encoder.layers.6.self_attn.out_proj.weight', 'text_model.encoder.layers.6.self_attn.out_proj.bias', 'text_model.encoder.layers.6.layer_norm2.weight', 'text_model.encoder.layers.6.layer_norm2.bias', 'text_model.encoder.layers.6.mlp.fc1.weight', 'text_model.encoder.layers.6.mlp.fc1.bias', 'text_model.encoder.layers.6.mlp.fc2.weight', 'text_model.encoder.layers.6.mlp.fc2.bias', 'text_model.encoder.layers.7.layer_norm1.weight', 'text_model.encoder.layers.7.layer_norm1.bias', 'text_model.encoder.layers.7.self_attn.q_proj.weight', 'text_model.encoder.layers.7.self_attn.q_proj.bias', 'text_model.encoder.layers.7.self_attn.k_proj.weight', 'text_model.encoder.layers.7.self_attn.k_proj.bias', 'text_model.encoder.layers.7.self_attn.v_proj.weight', 'text_model.encoder.layers.7.self_attn.v_proj.bias', 'text_model.encoder.layers.7.self_attn.out_proj.weight', 'text_model.encoder.layers.7.self_attn.out_proj.bias', 'text_model.encoder.layers.7.layer_norm2.weight', 'text_model.encoder.layers.7.layer_norm2.bias', 'text_model.encoder.layers.7.mlp.fc1.weight', 'text_model.encoder.layers.7.mlp.fc1.bias', 'text_model.encoder.layers.7.mlp.fc2.weight', 'text_model.encoder.layers.7.mlp.fc2.bias', 'text_model.encoder.layers.8.layer_norm1.weight', 'text_model.encoder.layers.8.layer_norm1.bias', 'text_model.encoder.layers.8.self_attn.q_proj.weight', 'text_model.encoder.layers.8.self_attn.q_proj.bias', 'text_model.encoder.layers.8.self_attn.k_proj.weight', 'text_model.encoder.layers.8.self_attn.k_proj.bias', 'text_model.encoder.layers.8.self_attn.v_proj.weight', 'text_model.encoder.layers.8.self_attn.v_proj.bias', 'text_model.encoder.layers.8.self_attn.out_proj.weight', 'text_model.encoder.layers.8.self_attn.out_proj.bias', 'text_model.encoder.layers.8.layer_norm2.weight', 'text_model.encoder.layers.8.layer_norm2.bias', 'text_model.encoder.layers.8.mlp.fc1.weight', 'text_model.encoder.layers.8.mlp.fc1.bias', 'text_model.encoder.layers.8.mlp.fc2.weight', 'text_model.encoder.layers.8.mlp.fc2.bias', 'text_model.encoder.layers.9.layer_norm1.weight', 'text_model.encoder.layers.9.layer_norm1.bias', 'text_model.encoder.layers.9.self_attn.q_proj.weight', 'text_model.encoder.layers.9.self_attn.q_proj.bias', 'text_model.encoder.layers.9.self_attn.k_proj.weight', 'text_model.encoder.layers.9.self_attn.k_proj.bias', 'text_model.encoder.layers.9.self_attn.v_proj.weight', 'text_model.encoder.layers.9.self_attn.v_proj.bias', 'text_model.encoder.layers.9.self_attn.out_proj.weight', 'text_model.encoder.layers.9.self_attn.out_proj.bias', 'text_model.encoder.layers.9.layer_norm2.weight', 'text_model.encoder.layers.9.layer_norm2.bias', 'text_model.encoder.layers.9.mlp.fc1.weight', 'text_model.encoder.layers.9.mlp.fc1.bias', 'text_model.encoder.layers.9.mlp.fc2.weight', 'text_model.encoder.layers.9.mlp.fc2.bias', 'text_model.encoder.layers.10.layer_norm1.weight', 'text_model.encoder.layers.10.layer_norm1.bias', 'text_model.encoder.layers.10.self_attn.q_proj.weight', 'text_model.encoder.layers.10.self_attn.q_proj.bias', 'text_model.encoder.layers.10.self_attn.k_proj.weight', 'text_model.encoder.layers.10.self_attn.k_proj.bias', 'text_model.encoder.layers.10.self_attn.v_proj.weight', 'text_model.encoder.layers.10.self_attn.v_proj.bias', 'text_model.encoder.layers.10.self_attn.out_proj.weight', 'text_model.encoder.layers.10.self_attn.out_proj.bias', 'text_model.encoder.layers.10.layer_norm2.weight', 'text_model.encoder.layers.10.layer_norm2.bias', 'text_model.encoder.layers.10.mlp.fc1.weight', 'text_model.encoder.layers.10.mlp.fc1.bias', 'text_model.encoder.layers.10.mlp.fc2.weight', 'text_model.encoder.layers.10.mlp.fc2.bias', 'text_model.encoder.layers.11.layer_norm1.weight', 'text_model.encoder.layers.11.layer_norm1.bias', 'text_model.encoder.layers.11.self_attn.q_proj.weight', 'text_model.encoder.layers.11.self_attn.q_proj.bias', 'text_model.encoder.layers.11.self_attn.k_proj.weight', 'text_model.encoder.layers.11.self_attn.k_proj.bias', 'text_model.encoder.layers.11.self_attn.v_proj.weight', 'text_model.encoder.layers.11.self_attn.v_proj.bias', 'text_model.encoder.layers.11.self_attn.out_proj.weight', 'text_model.encoder.layers.11.self_attn.out_proj.bias', 'text_model.encoder.layers.11.layer_norm2.weight', 'text_model.encoder.layers.11.layer_norm2.bias', 'text_model.encoder.layers.11.mlp.fc1.weight', 'text_model.encoder.layers.11.mlp.fc1.bias', 'text_model.encoder.layers.11.mlp.fc2.weight', 'text_model.encoder.layers.11.mlp.fc2.bias', 'text_model.final_layer_norm.weight', 'text_model.final_layer_norm.bias', 'text_projection.weight']
2024-09-03 17:47:38,685 - root - INFO - Requested to load SDXLClipModel
2024-09-03 17:47:38,685 - root - INFO - Loading 1 new model
2024-09-03 17:47:38,867 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-09-03 17:47:40,414 - root - INFO - Requested to load Flux
2024-09-03 17:47:40,414 - root - INFO - Loading 1 new model
2024-09-03 17:47:41,410 - root - INFO - loaded completely 0.0 11350.048889160156 True
2024-09-03 17:47:41,460 - root - ERROR - !!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x3072)
2024-09-03 17:47:41,460 - root - ERROR - Traceback (most recent call last):
  File "/home/pi/codes/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/pi/codes/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/pi/codes/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/pi/codes/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/nodes.py", line 209, in sampling
    x = denoise_controlnet(
  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/utils.py", line 419, in denoise_controlnet
    block_res_samples, single_block_res_samples = controlnet(
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/misto_controlnet.py", line 218, in forward
    vec = vec + self.vector_in(y)
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/custom_nodes/MistoControlNet-Flux-dev/modules/utils.py", line 87, in forward
    return self.out_layer(self.silu(self.in_layer(x)))
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pi/codes/ComfyUI/comfy_venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x3072)

2024-09-03 17:47:41,460 - root - INFO - Prompt executed in 4.26 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":12,"last_link_id":12,"nodes":[{"id":2,"type":"SaveImage","pos":{"0":1319,"1":229,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":11,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":1}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":4,"type":"VAELoader","pos":{"0":134,"1":264,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[3],"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":5,"type":"CLIPTextEncode","pos":{"0":92,"1":399,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":400,"1":200},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":6}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"shape":3,"tooltip":"A conditioning containing the embedded text used to guide the diffusion model."}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["Two african women"]},{"id":6,"type":"CLIPTextEncode","pos":{"0":79,"1":662,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":400,"1":200},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":7}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[5],"slot_index":0,"shape":3,"tooltip":"A conditioning containing the embedded text used to guide the diffusion model."}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["low quality"]},{"id":1,"type":"KSamplerTheMisto","pos":{"0":712,"1":252,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":330,"1":234},"flags":{},"order":10,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":2,"slot_index":0},{"name":"ae","type":"VAE","link":3,"slot_index":1},{"name":"positive","type":"CONDITIONING","link":4,"slot_index":2},{"name":"negative","type":"CONDITIONING","link":5},{"name":"controlnet_condition","type":"ControlNetCondition","link":8,"slot_index":4}],"outputs":[{"name":"image","type":"IMAGE","links":[1],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSamplerTheMisto"},"widgets_values":[1,4,598896362400145,"randomize",20]},{"id":9,"type":"LoadTheMistoFluxControlNet","pos":{"0":-276,"1":751,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"ControlNet","type":"MistoFluxControlNet","links":[9],"shape":3}],"properties":{"Node name for S&R":"LoadTheMistoFluxControlNet"},"widgets_values":["mistoline_flux.dev_v1.bin"]},{"id":7,"type":"DualCLIPLoader","pos":{"0":-316,"1":482,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":106},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[6,7],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["clip_l.safetensors","t5xxl_fp8_e4m3fn.safetensors","sdxl"]},{"id":3,"type":"UNETLoader","pos":{"0":140,"1":87,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":82},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[2],"shape":3}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev.safetensors","fp8_e4m3fn"]},{"id":11,"type":"PreviewImage","pos":{"0":140,"1":1213,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":246},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":11}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":12,"type":"LoadImage","pos":{"0":-748,"1":1063,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":314},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[12],"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_00006_.png","image"]},{"id":10,"type":"LineArtPreprocessor","pos":{"0":-352,"1":1066,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":82},"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":12,"slot_index":0}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[10,11],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"LineArtPreprocessor"},"widgets_values":["enable",1024]},{"id":8,"type":"ApplyTheMistoFluxControlNet","pos":{"0":132,"1":948,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":393,"1":102},"flags":{},"order":8,"mode":0,"inputs":[{"name":"controlnet","type":"MistoFluxControlNet","link":9,"slot_index":0},{"name":"image","type":"IMAGE","link":10,"slot_index":1}],"outputs":[{"name":"controlnet_condition","type":"ControlNetCondition","links":[8],"shape":3},{"name":"cond_image","type":"IMAGE","links":null,"shape":3}],"properties":{"Node name for S&R":"ApplyTheMistoFluxControlNet"},"widgets_values":[512,0.5]}],"links":[[1,1,0,2,0,"IMAGE"],[2,3,0,1,0,"MODEL"],[3,4,0,1,1,"VAE"],[4,5,0,1,2,"CONDITIONING"],[5,6,0,1,3,"CONDITIONING"],[6,7,0,5,0,"CLIP"],[7,7,0,6,0,"CLIP"],[8,8,0,1,4,"ControlNetCondition"],[9,9,0,8,0,"MistoFluxControlNet"],[10,10,0,8,1,"IMAGE"],[11,10,0,11,0,"IMAGE"],[12,12,0,10,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9090909090909092,"offset":[794.0810783471068,-237.5076435537212]}},"version":0.4}

**Comment by baizh0u** [comment]
Are you have already refreshed the website? I mean the comfyUI website.

**Comment by dave-ct** [comment]
Yes, updated everything and then restarted and reloaded the web UI.  I had
the same issue before updating as well.

**Comment by baizh0u** [comment]
Can you share your screenshot of ComfyUI with the full workflow as well?

**Comment by dave-ct** [comment]
@baizh0u -  here are the screenshots of the workflow and the issue.  Anything else that might help then please let me know.  Thanks

![Screenshot from 2024-09-04 08-47-31](https://github.com/user-attachments/assets/bb0dc85d-49aa-4fc7-aa29-624e64c0d4e9)

![Screenshot from 2024-09-04 08-46-58](https://github.com/user-attachments/assets/53cf3206-9ea2-459d-860e-50f32b65e797)

![Screenshot from 2024-09-04 08-47-14](https://github.com/user-attachments/assets/ecc558cc-7ba9-4ed1-b858-22a051b818d3)

**Comment by dave-ct** [comment]
@baizh0u that fixed it, thanks for the pointer there.  

In case anyone else hits the same issue attached is to corrected JSON file I used. 

[misto_working_simple.json](https://github.com/user-attachments/files/16869108/misto_working_simple.json)

**Comment by dave-ct** [comment]
Fixed
